trigger: none

pool:
  vmImage: ubuntu-latest

#schedules:
#  - cron: "*/3 * * * *"
#    displayName: Run every 3 minutes
#    branches:
#      include:
#        - test
#    always: true

stages:

- stage: Build
  displayName: Build stage

  jobs:
   - job: Build

     steps:
     - task: UsePythonVersion@0
       inputs:
        versionSpec: '$(pythonVersion)'
       displayName: 'Use Python $(pythonVersion)'

     - script: python main.py