trigger: 
- main

pool:
  name: default

stages:

- stage: ImageBuild
  displayName: Triggering TBS to build an image

  jobs:
   - job: Image_Building_job
     steps:
     - task: SSH@0
       inputs:
         sshEndpoint: 'tanzu-kp'
         runOptions: 'commands'
         commands: |
            kubectl config use-context tkc-tbs
            kubectl patch storageclass tanzu-tag-storage -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
            kp image patch --git-=$(Build.SourceVersion)
         readyTimeout: '20000'