trigger: 
- main

pool:
  vmImage: ubuntu-latest

stages:

- stage: ImageBuild
  displayName: Triggering TBS to build an image

  jobs:
   - job: Image_Building_job
     steps:
     - script: |
          curl -L https://<url_to_pivnet_cli> -o pivnet
          chmod u+x pivnet
       displayName: 'Download Tanzu Network CLI'
     - script: ./pivnet login --api-token $(api-token)
       displayName: 'Log In To Tanzu Network'
     - script: |
         ./pivnet download-product-files --product-slug='build-service' --release-version='1.2.1' --product-file-id='970671' 
         mv kp-linux-0.3.0 kp
         chmod u+x kp
       displayName: 'Download kpack cli'
     - script: |
         kubectl config set-cluster demo --server=$(k8s-server)
         kubectl config set-credentials azure-pipelines --token=$(k8s-token)
         kubectl config set-context demo --user=azure-pipelines --cluster=demo
         kubectl config set-cluster demo --embed-certs --certificate-authority <(echo $(k8s-ca-crt-b64) | base64 --decode)
         kubectl config use-context demo
       displayName: 'Setup Kubectl'
     - script: |
         ./kp image patch --git-revision=$(Build.SourceVersion) --wait spring-petclinic
       displayName: 'Patch Image Commit SHA'