trigger: 
- main

pool:
  name: default

stages:

- stage: ImageBuild
  displayName: Triggering TBS to build an image

  jobs:
   - job: Image_Building_job
     steps:
     - task: SSH@0
       inputs:
         sshEndpoint: 'tanzu-kp'
         runOptions: 'commands'
         commands: |
            kubectl config use-context $(Context)
            kubectl patch storageclass $(Storage_Class) -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
            kp image create image$(Build.BuildNumber) --tag $(Url_Tag) --git $(Git_Url)
         readyTimeout: '20000'